"""Minimal VCD writer.

Used by `tools/sim` to archive a directed test's captured signal trace as a
real VCD (viewable in Surfer / GTKWave / the tools the puzzle README already
points at), independent of whatever the simulator itself dumps. Not a
general-purpose writer — see model.py's docstring.
"""

from __future__ import annotations

from pathlib import Path

from .model import VcdDocument

# Printable ASCII identifier alphabet VCD tools conventionally use for
# generated id codes (excludes '$' and whitespace).
_ID_ALPHABET = [chr(c) for c in range(33, 127) if chr(c) != "$"]


def _make_identifier(index: int) -> str:
    """Base-len(_ID_ALPHABET) encoding of `index`, matching common VCD writers."""
    base = len(_ID_ALPHABET)
    if index < base:
        return _ID_ALPHABET[index]
    digits = []
    n = index
    while n > 0:
        digits.append(_ID_ALPHABET[n % base])
        n //= base
    return "".join(reversed(digits))


def _value_line(ident: str, value: str, width: int) -> str:
    if width == 1:
        return f"{value}{ident}"
    return f"b{value} {ident}"


def write_vcd(
    path: str | Path,
    timescale: str,
    signals: list[tuple[str, int]],
    changes: list[tuple[int, str, str]],
    scope: str = "tb",
) -> None:
    """Write a minimal VCD file.

    Args:
        path: output file path.
        timescale: verbatim `$timescale` body, e.g. "1ps".
        signals: list of (name, width) declaring the variables, in the order
            they should be emitted.
        changes: list of (time, name, value) value-change events. `value` is
            a bit string ("0"/"1"/"x"/"z" for width 1, or a same-length
            binary/x/z string for wider signals) already normalized to the
            signal's declared width by the caller.
        scope: single `$scope module <scope> $end` wrapping all signals.
    """
    ident_by_name = {name: _make_identifier(i) for i, (name, _width) in enumerate(signals)}
    width_by_name = {name: width for name, width in signals}

    lines: list[str] = []
    lines.append("$date")
    lines.append("    generated by tools/vcd (sky130-asic-puzzle)")
    lines.append("$end")
    lines.append("$version")
    lines.append("    tools/vcd minimal writer")
    lines.append("$end")
    lines.append("$timescale")
    lines.append(f"    {timescale}")
    lines.append("$end")
    lines.append(f"$scope module {scope} $end")
    for name, width in signals:
        lines.append(f"$var wire {width} {ident_by_name[name]} {name} $end")
    lines.append("$upscope $end")
    lines.append("$enddefinitions $end")

    grouped: dict[int, list[tuple[str, str]]] = {}
    for time, name, value in changes:
        grouped.setdefault(time, []).append((name, value))

    ordered_times = sorted(grouped)
    first_time = ordered_times[0] if ordered_times else 0

    lines.append("$dumpvars")
    for name, width in signals:
        initial = next((v for n, v in grouped.get(first_time, []) if n == name), None)
        if initial is None:
            initial = "x" * width
        lines.append(_value_line(ident_by_name[name], initial, width))
    lines.append("$end")

    for time in ordered_times:
        if time == first_time:
            continue
        lines.append(f"#{time}")
        for name, value in grouped[time]:
            lines.append(_value_line(ident_by_name[name], value, width_by_name[name]))

    Path(path).write_text("\n".join(lines) + "\n")


def document_to_vcd(doc: VcdDocument, path: str | Path) -> None:
    """Write a previously-parsed VcdDocument back out (round-trip helper)."""
    signals = [(v.name, v.width) for v in doc.vars]
    name_by_id = {v.identifier: v.name for v in doc.vars}
    changes = [(c.time, name_by_id[c.identifier], c.value) for c in doc.changes if c.identifier in name_by_id]
    write_vcd(path, doc.timescale, signals, changes)
