#!/usr/bin/env python3
"""Independent review addendum, claim 6: failure-message sweep.

Written for the addendum review and deliberately independent of tools/sim:
this script generates its own Verilog testbench text, invokes iverilog/vvp
directly, and decodes O[7:0] with its own decoder. The only shared inputs
are the extracted netlist (the artifact under review), the sky130 behavioural
models (ground truth for the cells), and the accepted 121-bit word (taken
from evidence/puzzle-solve.md; its correctness is claim 2, not claim 6 —
this script re-verifies it drives `success` before using it to build
near-misses).

Input families swept (each replayed gate-level through Icarus):
  - the accepted word (control), and the 7 structured failures lead3 used
  - population probes (1, 2, 60, 119, 120 ones)
  - seeded random words at densities ~0.18, 0.5, 0.9
  - every single-bit flip of the accepted word (121 words)
  - star moves (one accepted 1 relocated to a random 0 position)
  - rule-targeted near-misses generated by SAT (satisfy the published
    row/column/no-touching rules but are not the accepted word)

Run from the repo root:

    .sim-work/review-venv/bin/python \
        evidence/independent-review-addendum-messages.py
"""

import random
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
NETLIST = REPO / ".sim-work/independent-review/puzzle-extracted.v"
WORK = REPO / ".sim-work/indrev-addendum/messages"
PDK_VERILOG = Path.home() / ".volare/sky130A/libs.ref/sky130_fd_sc_hd/verilog"
PRIMITIVES = PDK_VERILOG / "primitives.v"
BEHAVIOURAL = PDK_VERILOG / "sky130_fd_sc_hd.v"

TOTAL_CYCLES = 190
ACTIVE_START = 4  # rst_n deasserts at t=3, enable window is t in [4, 125)
ACTIVE_LEN = 121

ACCEPTED = (
    "0000000101010000100000000000010101010000000000001010000001000001"
    "000000100000101000010000000100000010000010010001010000000"
)
assert len(ACCEPTED) == 121

TB = f"""`timescale 1ns/1ps
module tb;
  reg clk = 0, rst_n = 0, enable = 0, I = 0;
  wire success;
  wire o0, o1, o2, o3, o4, o5, o6, o7;
  reg word [0:{ACTIVE_LEN - 1}];
  integer t;
  puzzle dut (.I (I), .clk (clk), .enable (enable), .rst_n (rst_n),
    .success (success),
    .\\O[0] (o0), .\\O[1] (o1), .\\O[2] (o2), .\\O[3] (o3),
    .\\O[4] (o4), .\\O[5] (o5), .\\O[6] (o6), .\\O[7] (o7));
  always #5 clk = ~clk;
  initial begin
    $readmemb("word.mem", word);
    for (t = 0; t < {TOTAL_CYCLES}; t = t + 1) begin
      rst_n = (t >= 3);
      enable = (t >= {ACTIVE_START} && t < {ACTIVE_START + ACTIVE_LEN});
      I = (t >= {ACTIVE_START} && t < {ACTIVE_START + ACTIVE_LEN})
          ? word[t - {ACTIVE_START}] : 1'b0;
      #4;
      $display("CYCLE %0d %b%b%b%b%b%b%b%b %b",
               t, o7, o6, o5, o4, o3, o2, o1, o0, success);
      #6;
    end
    $finish;
  end
endmodule
"""


def compile_tb() -> Path:
    WORK.mkdir(parents=True, exist_ok=True)
    tb_path = WORK / "tb.v"
    tb_path.write_text(TB)
    out = WORK / "sim.vvp"
    cmd = ["iverilog", "-g2005", "-o", str(out), "-D", "FUNCTIONAL",
           "-D", "UNIT_DELAY=#1", "-s", "tb",
           str(tb_path), str(NETLIST), str(PRIMITIVES), str(BEHAVIOURAL)]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if proc.returncode != 0:
        sys.exit(f"iverilog failed:\n{proc.stderr}")
    return out


CYCLE_RE = re.compile(r"^CYCLE (\d+) ([01xz]{8}) ([01xz])$")


def run_word(vvp_path: Path, word: str, label: str):
    d = WORK / "runs" / label
    d.mkdir(parents=True, exist_ok=True)
    (d / "word.mem").write_text("\n".join(word) + "\n")
    proc = subprocess.run(["vvp", str(vvp_path)], capture_output=True,
                          text=True, timeout=120, cwd=d)
    if proc.returncode != 0:
        sys.exit(f"vvp failed for {label}:\n{proc.stderr}")
    samples = {}
    success_cycles = []
    for line in proc.stdout.splitlines():
        m = CYCLE_RE.match(line.strip())
        if not m:
            continue
        t = int(m.group(1))
        samples[t] = m.group(2)  # o7..o0 as printed
        if m.group(3) == "1":
            success_cycles.append(t)
    assert len(samples) == TOTAL_CYCLES, (label, len(samples))
    return samples, success_cycles


def decode(samples, order: str) -> str:
    """One char per cycle; U+00B7 (outside ASCII) where not printable."""
    chars = []
    for t in range(TOTAL_CYCLES):
        bits = samples[t]  # o7..o0
        if "x" in bits or "z" in bits:
            chars.append("×")
            continue
        if order == "lsb":  # O[i] is bit i of the byte
            val = int(bits, 2)
        else:  # O[i] is bit 7-i
            val = int(bits[::-1], 2)
        chars.append(chr(val) if 0x20 <= val <= 0x7E else "·")
    return "".join(chars)


def printable_runs(decoded: str, min_len=3):
    return [m.group(0) for m in re.finditer(r"[ -~]{%d,}" % min_len, decoded)]


def classify(samples, success_cycles):
    lsb = decode(samples, "lsb")
    runs = printable_runs(lsb)
    longest = max(runs, key=len) if runs else ""
    msb_runs = printable_runs(decode(samples, "msb"), min_len=4)
    return longest, runs, lsb, msb_runs


# ---------------------------------------------------------------- word sets
def neighbours(pos):
    r, c = divmod(pos, 11)
    for dr in (-1, 0, 1):
        for dc in (-1, 0, 1):
            if dr == dc == 0:
                continue
            nr, nc = r + dr, c + dc
            if 0 <= nr < 11 and 0 <= nc < 11:
                yield nr * 11 + nc


def sat_near_valid(n_words):
    """Words satisfying the *published* rules (2/row, 2/col, no touching)
    that are not the accepted word — naive encodings, glucose backend."""
    from itertools import combinations

    from pysat.solvers import Solver

    clauses = []

    def exactly2(varset):
        for triple in combinations(varset, 3):  # at most 2
            clauses.append([-v for v in triple])
        for sub in combinations(varset, len(varset) - 1):  # at least 2
            clauses.append(list(sub))

    for r in range(11):
        exactly2([r * 11 + c + 1 for c in range(11)])
    for c in range(11):
        exactly2([r * 11 + c + 1 for r in range(11)])
    for a in range(121):
        for b in neighbours(a):
            if b > a:
                clauses.append([-(a + 1), -(b + 1)])
    clauses.append([-(p + 1) if bit == "1" else (p + 1)
                    for p, bit in enumerate(ACCEPTED)])
    words = []
    with Solver(name="glucose42", bootstrap_with=clauses) as s:
        while len(words) < n_words and s.solve():
            model = set(v for v in s.get_model() if v > 0)
            word = "".join("1" if p + 1 in model else "0" for p in range(121))
            words.append(word)
            s.add_clause([-(p + 1) if b == "1" else (p + 1)
                          for p, b in enumerate(word)])
    return words


def build_words():
    words = {"accepted": ACCEPTED}
    words["all-zero"] = "0" * 121
    words["all-one"] = "1" * 121
    words["alt-01"] = ("01" * 61)[:121]
    words["alt-10"] = ("10" * 61)[:121]
    words["complement"] = "".join("1" if b == "0" else "0" for b in ACCEPTED)
    words["one-first"] = "1" + "0" * 120
    words["one-last"] = "0" * 120 + "1"
    # population probes
    words["pop-2"] = "11" + "0" * 119
    words["pop-60"] = ("1" * 60).ljust(121, "0")
    words["pop-119"] = "0" * 2 + "1" * 119
    words["pop-120-zero-first"] = "0" + "1" * 120
    words["pop-120-zero-last"] = "1" * 120 + "0"
    rng = random.Random(20260810)
    for i in range(10):
        words[f"rand-half-{i}"] = "".join(
            rng.choice("01") for _ in range(121))
    for i in range(5):
        words[f"rand-sparse-{i}"] = "".join(
            "1" if rng.random() < 22 / 121 else "0" for _ in range(121))
    for i in range(5):
        words[f"rand-dense-{i}"] = "".join(
            "1" if rng.random() < 0.9 else "0" for _ in range(121))
    for pos in range(121):
        flipped = list(ACCEPTED)
        flipped[pos] = "1" if flipped[pos] == "0" else "0"
        words[f"flip-{pos:03d}"] = "".join(flipped)
    ones = [p for p, b in enumerate(ACCEPTED) if b == "1"]
    zeros = [p for p, b in enumerate(ACCEPTED) if b == "0"]
    for i in range(10):
        src = rng.choice(ones)
        dst = rng.choice(zeros)
        moved = list(ACCEPTED)
        moved[src], moved[dst] = "0", "1"
        words[f"star-move-{i}"] = "".join(moved)
    for i, w in enumerate(sat_near_valid(8)):
        words[f"near-valid-{i}"] = w
    return words


def main():
    vvp_path = compile_tb()
    words = build_words()
    print(f"words to replay: {len(words)}")
    tally = Counter()
    families = {}
    anomalies = []
    for label, word in sorted(words.items()):
        samples, success_cycles = run_word(vvp_path, word, label)
        longest, runs, lsb, msb_runs = classify(samples, success_cycles)
        start = lsb.find(longest) if longest else -1
        tally[(longest, start)] += 1
        fam = label.rstrip("0123456789").rstrip("-")
        families.setdefault(fam, Counter())[longest] += 1
        is_accepted_word = word == ACCEPTED
        if bool(success_cycles) != is_accepted_word:
            anomalies.append(
                f"SUCCESS ANOMALY {label}: success_cycles="
                f"{success_cycles[:4]}... word==accepted={is_accepted_word}")
        expected = {"(* TWO STARS *)", "EMPTY SKY", "BIG BANG", "TRY AGAIN"}
        if longest not in expected:
            anomalies.append(f"MESSAGE ANOMALY {label}: longest={longest!r} "
                             f"runs={runs!r}")
        extra = [r for r in runs if r != longest and len(r) >= 4]
        if extra:
            anomalies.append(f"EXTRA RUNS {label}: {extra!r}")
        surprising_msb = [r for r in msb_runs
                          if not set(r) <= {"B", "D", "F", "H", "J"}]
        if surprising_msb:
            anomalies.append(f"MSB-ORDER RUNS {label}: {msb_runs!r}")
    print("\n== per-family longest-printable tally ==")
    for fam in sorted(families):
        parts = ", ".join(f"{msg!r}:{n}" for msg, n in
                          sorted(families[fam].items()))
        print(f"{fam}: {parts}")
    print("\n== overall (message, start-cycle) tally ==")
    for (msg, start), n in sorted(tally.items()):
        print(f"{msg!r} @ cycle {start}: {n}")
    print(f"\nanomalies: {len(anomalies)}")
    for a in anomalies:
        print(a)


if __name__ == "__main__":
    main()
